#!/usr/bin/env bats
#
# bin/plug against a throwaway upstream and a throwaway toolkit root.
# PLUG_REPO_ROOT and PLUG_CACHE_DIR point under $BATS_TEST_TMPDIR, so the real
# repo's vendor/, plugins.lock and the real cache are never touched.

load helper

setup() {
  git_env
  PLUG="$REPO_ROOT/bin/plug"
  TK="$BATS_TEST_TMPDIR/toolkit"
  UP="$BATS_TEST_TMPDIR/upstream"
  export PLUG_REPO_ROOT="$TK"
  export PLUG_CACHE_DIR="$BATS_TEST_TMPDIR/cache"
  mkdir -p "$TK/skills"
  make_upstream "$UP"
}

# make_upstream DIR — a repo holding skills/alpha and a nested, executable skills/beta.
make_upstream() {
  local up="$1"
  git init -q -b main "$up"
  mkdir -p "$up/skills/alpha" "$up/skills/beta/scripts/deep"
  skill_md alpha >"$up/skills/alpha/SKILL.md"
  skill_md beta >"$up/skills/beta/SKILL.md"
  printf '#!/bin/sh\necho hi\n' >"$up/skills/beta/scripts/run.sh"
  chmod +x "$up/skills/beta/scripts/run.sh"
  printf 'nested\n' >"$up/skills/beta/scripts/deep/notes.txt"
  git -C "$up" add -A
  git -C "$up" commit -q -m init
}

skill_md() {
  printf -- '---\nname: %s\ndescription: %s does one thing. Use when a test needs it.\n---\nbody\n' "$1" "$1"
}

conf() { printf '%s\n' "$@" >"$TK/plugins.conf"; }

std_conf() {
  conf "source up file://$UP main" "skill up skills/alpha" "skill up skills/beta"
}

# snapshot — every vendored file with its mode and checksum, one per line.
snapshot() {
  (cd "$TK" && find vendor plugins.lock -exec ls -ld {} + 2>/dev/null |
    awk '{print $1, $NF}' && find vendor -type f -exec cksum {} + | sort)
}

# run_clean CMD... — run, then fail on a non-zero exit OR a shell abort message:
# under bash 3.2 an unbound-variable abort inside plug exits 0 (its EXIT trap).
run_clean() {
  run "$@"
  [ "$status" -eq 0 ] || return 1
  case "$output" in *"unbound variable"* | *"syntax error"*) return 1 ;; esac
}

@test "plug: sync vendors each skill and pins it in the lock" {
  std_conf
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ -f "$TK/vendor/skills/alpha/SKILL.md" ]
  [ -x "$TK/vendor/skills/beta/scripts/run.sh" ]
  local sha
  sha="$(git -C "$UP" rev-parse HEAD)"
  grep -qx "source up $sha $(date -u +%Y-%m-%d)" "$TK/plugins.lock"
  grep -qx "skill up skills/alpha alpha $(git -C "$UP" rev-parse HEAD:skills/alpha)" "$TK/plugins.lock"
  grep -qx "skill up skills/beta beta $(git -C "$UP" rev-parse HEAD:skills/beta)" "$TK/plugins.lock"
  head -1 "$TK/plugins.lock" | grep -q 'generated by bin/plug'
  [[ "$output" == *"./install.sh skills"* ]] || false
}

@test "plug: the local tree hash matches upstream for exec bits and nested dirs" {
  std_conf
  "$PLUG" sync >/dev/null
  rm -rf "$PLUG_CACHE_DIR" # offline, no cache: the check hashes vendor/ itself
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
  chmod -x "$TK/vendor/skills/beta/scripts/run.sh"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"vendor/skills/beta differs"* ]] || false
}

@test "plug: a second sync changes nothing" {
  std_conf
  "$PLUG" sync >/dev/null
  local before
  before="$(snapshot)"
  cp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [[ "$output" == *"up to date"* ]] || false
  [[ "$output" != *"install.sh"* ]] || false
  cmp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  [ "$(snapshot)" = "$before" ]
}

@test "plug: a no-op sync keeps the lock's date" {
  std_conf
  "$PLUG" sync >/dev/null
  sed -E 's/^(source up [0-9a-f]+) .*/\1 2000-01-01/' "$TK/plugins.lock" >"$TK/l" && mv "$TK/l" "$TK/plugins.lock"
  "$PLUG" sync >/dev/null
  grep -q '^source up [0-9a-f]* 2000-01-01$' "$TK/plugins.lock"
}

@test "plug: sync keeps the pin when upstream moves; update chases it" {
  std_conf
  "$PLUG" sync >/dev/null
  local old new
  old="$(git -C "$UP" rev-parse HEAD)"
  printf 'v2\n' >>"$UP/skills/alpha/SKILL.md"
  git -C "$UP" commit -q -am v2
  new="$(git -C "$UP" rev-parse HEAD)"

  run "$PLUG" sync
  [ "$status" -eq 0 ]
  grep -q "^source up $old " "$TK/plugins.lock"
  run grep -q v2 "$TK/vendor/skills/alpha/SKILL.md"
  [ "$status" -ne 0 ]

  run "$PLUG" update
  [ "$status" -eq 0 ]
  [[ "$output" == *"~ alpha"* ]] || false
  grep -q "^source up $new " "$TK/plugins.lock"
  grep -q v2 "$TK/vendor/skills/alpha/SKILL.md"
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug: update <src> re-resolves only that source" {
  local up2="$BATS_TEST_TMPDIR/upstream2"
  git init -q -b main "$up2"
  mkdir -p "$up2/gamma"
  skill_md gamma >"$up2/gamma/SKILL.md"
  git -C "$up2" add -A
  git -C "$up2" commit -q -m init
  conf "source up file://$UP main" "skill up skills/alpha" \
    "source two file://$up2 main" "skill two gamma"
  "$PLUG" sync >/dev/null
  local up_old
  up_old="$(git -C "$UP" rev-parse HEAD)"
  printf 'v2\n' >>"$UP/skills/alpha/SKILL.md"
  git -C "$UP" commit -q -am v2
  printf 'v2\n' >>"$up2/gamma/SKILL.md"
  git -C "$up2" commit -q -am v2

  run "$PLUG" update two
  [ "$status" -eq 0 ]
  grep -q "^source up $up_old " "$TK/plugins.lock"
  grep -q "^source two $(git -C "$up2" rev-parse HEAD) " "$TK/plugins.lock"

  run "$PLUG" update nosuch
  [ "$status" -ne 0 ]
  [[ "$output" == *"no source 'nosuch'"* ]] || false
}

@test "plug: removing a skill line deletes its copy and its lock line" {
  std_conf
  "$PLUG" sync >/dev/null
  conf "source up file://$UP main" "skill up skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [[ "$output" == *"- beta"* ]] || false
  [[ "$output" == *"./install.sh skills"* ]] || false
  [ ! -e "$TK/vendor/skills/beta" ]
  run grep -q ' beta ' "$TK/plugins.lock"
  [ "$status" -ne 0 ]
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug: removing every source removes the lock and vendor/" {
  std_conf
  "$PLUG" sync >/dev/null
  conf "# nothing vendored"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ ! -e "$TK/plugins.lock" ]
  [ ! -e "$TK/vendor" ]
}

@test "plug: two sources claiming one name is a sync error" {
  local up2="$BATS_TEST_TMPDIR/upstream2"
  make_upstream "$up2"
  conf "source up file://$UP main" "skill up skills/alpha" \
    "source two file://$up2 main" "skill two skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"'alpha' claimed twice"* ]] || false
  [ ! -e "$TK/vendor" ]
  [ ! -e "$TK/plugins.lock" ]
}

@test "plug: a vendored name colliding with a local skill is a sync error" {
  mkdir -p "$TK/skills/alpha"
  std_conf
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"collides with local skills/alpha"* ]] || false
  [ ! -e "$TK/vendor" ]
  run "$PLUG" list
  [[ "$output" == *"warn"*"collides"* ]] || false
}

@test "plug: a path missing at the pinned SHA fails clearly and leaves vendor/ alone" {
  std_conf
  "$PLUG" sync >/dev/null
  local before
  before="$(snapshot)"
  conf "source up file://$UP main" "skill up skills/alpha" "skill up skills/beta" "skill up skills/nope"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"no directory 'skills/nope'"* ]] || false
  [ "$(snapshot)" = "$before" ]
  # a file is not a skill directory either
  conf "source up file://$UP main" "skill up skills/alpha/SKILL.md"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [ "$(snapshot)" = "$before" ]
}

@test "plug: doctor and --check catch a hand edit; sync restores it" {
  std_conf
  "$PLUG" sync >/dev/null
  printf 'tampered\n' >>"$TK/vendor/skills/alpha/SKILL.md"
  run "$PLUG" doctor
  [ "$status" -eq 1 ]
  [[ "$output" == *"FAIL  vendor/skills/alpha differs"* ]] || false
  [[ "$output" == *"ok    vendor/skills/beta"* ]] || false
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  "$PLUG" sync >/dev/null
  run grep -q tampered "$TK/vendor/skills/alpha/SKILL.md"
  [ "$status" -ne 0 ]
  run "$PLUG" doctor
  [ "$status" -eq 0 ]
}

@test "plug: --check flags a stray vendor dir, a missing copy and a conf/lock mismatch" {
  std_conf
  "$PLUG" sync >/dev/null
  mkdir -p "$TK/vendor/skills/stray"
  printf 'x\n' >"$TK/vendor/skills/stray/f"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"vendor/skills/stray is not in plugins.conf"* ]] || false
  rm -rf "$TK/vendor/skills/stray" "$TK/vendor/skills/beta"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"vendor/skills/beta is missing"* ]] || false
  "$PLUG" sync >/dev/null
  printf 'skill up skills/gone\n' >>"$TK/plugins.conf"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"gone (up:skills/gone) is not in plugins.lock"* ]] || false
}

@test "plug: --check fails clearly when the conf lists skills but no lock exists" {
  std_conf
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"no plugins.lock — run: plug sync"* ]] || false
}

@test "plug: a README beside the vendored skills is not drift" {
  std_conf
  "$PLUG" sync >/dev/null
  printf 'written by bin/plug\n' >"$TK/vendor/skills/README.md"
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
  "$PLUG" sync >/dev/null
  [ -f "$TK/vendor/skills/README.md" ]
}

@test "plug: offline with a cache miss fails clearly and leaves vendor/ alone" {
  conf "source up file://$BATS_TEST_TMPDIR/no-such-upstream main" "skill up skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"cannot fetch"* ]] || false
  [ ! -e "$TK/vendor" ]
  [ ! -e "$TK/plugins.lock" ]
  [ -z "$(find "$TK" -name '.plug-stage.*')" ]
}

@test "plug: offline with a cache hit still syncs the locked SHA" {
  std_conf
  "$PLUG" sync >/dev/null
  cp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  rm -rf "$TK/vendor"
  mv "$UP" "$UP.offline" # the network is gone
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ -f "$TK/vendor/skills/beta/SKILL.md" ]
  cmp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  # but chasing the ref needs the network
  run "$PLUG" update
  [ "$status" -eq 1 ]
  [[ "$output" == *"cannot fetch"* ]] || false
  [ -f "$TK/vendor/skills/beta/SKILL.md" ]
}

@test "plug: a no-op sync needs neither network nor cache" {
  std_conf
  "$PLUG" sync >/dev/null
  rm -rf "$PLUG_CACHE_DIR"
  mv "$UP" "$UP.offline"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [[ "$output" == *"up to date"* ]] || false
}

@test "plug: list shows pins and per-skill state" {
  std_conf
  run "$PLUG" list
  [ "$status" -eq 0 ]
  [[ "$output" == *"not locked"* ]] || false
  "$PLUG" sync >/dev/null
  run "$PLUG" list
  [[ "$output" == *"pinned $(git -C "$UP" rev-parse --short=12 HEAD)"* ]] || false
  [[ "$output" == *"alpha"*"vendored"* ]] || false
}

@test "plug: rejects a malformed conf with its line number" {
  conf "source up file://$UP main" "skill nosrc skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"plugins.conf:2:"* ]] || false
  conf "source up file://$UP" # missing ref
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"plugins.conf:1:"* ]] || false
}

@test "plug: help and unknown commands" {
  run "$PLUG" help
  [ "$status" -eq 0 ]
  [[ "$output" == *"sync --check"* ]] || false
  run "$PLUG" frobnicate
  [ "$status" -eq 2 ]
}

@test "plug: runs through a symlink, as installed in ~/bin" {
  mkdir -p "$BATS_TEST_TMPDIR/bin"
  ln -s "$PLUG" "$BATS_TEST_TMPDIR/bin/plug"
  unset PLUG_REPO_ROOT
  run "$BATS_TEST_TMPDIR/bin/plug" list
  [ "$status" -eq 0 ]
  # it found the real repo's conf without being told where it is
  [[ "$output" == *"source mattpocock"* ]] || false
}

@test "plug: shfmt discovery skips vendor/ via .editorconfig" {
  command -v shfmt >/dev/null 2>&1 || skip "shfmt not installed"
  local r="$BATS_TEST_TMPDIR/lintroot"
  mkdir -p "$r/vendor/skills/x" "$r/bin"
  cp "$REPO_ROOT/.editorconfig" "$r/"
  printf '#!/bin/bash\nif true; then\n      echo hi\nfi\n' >"$r/vendor/skills/x/bad.sh"
  printf '#!/bin/bash\necho ok\n' >"$r/bin/good"
  run bash -c "cd '$r' && shfmt -f ."
  [ "$output" = "bin/good" ]
  run bash -c "cd '$r' && shfmt -d -i 2 -ci ."
  [ "$status" -eq 0 ]
}

# ---------------------------------------------------------------------------
# Adversarial coverage: conf parsing, refs, upstream rewrites, atomicity, guards
# ---------------------------------------------------------------------------

# std_lock — the current lock with source dates stripped.
std_lock() { sed -E 's/^(source [^ ]+ [0-9a-f]+) .*/\1/' "$TK/plugins.lock"; }

@test "plug conf: tabs, trailing whitespace and indented comments parse like plain spaces" {
  std_conf
  "$PLUG" sync >/dev/null
  local want
  want="$(std_lock)"
  rm -rf "$TK/vendor" "$TK/plugins.lock"
  printf '  # indented comment\n \t \nsource\tup\tfile://%s\tmain  \t\nskill  up\tskills/alpha   \n\tskill up skills/beta\t\n' "$UP" >"$TK/plugins.conf"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ "$(std_lock)" = "$want" ]
}

@test "plug conf: a trailing slash or ./ in a skill path normalises, and a re-sync is a no-op" {
  conf "source up file://$UP main" "skill up ./skills/alpha/" "skill up skills/beta//"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  grep -qx "skill up skills/alpha alpha $(git -C "$UP" rev-parse HEAD:skills/alpha)" "$TK/plugins.lock"
  grep -q '^skill up skills/beta beta ' "$TK/plugins.lock"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [[ "$output" == *"up to date"* ]] || false
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug conf: each malformed line is refused with its line number, nothing written" {
  local bad
  for bad in \
    "skill up skills/alpha|source up file://$UP main|1" \
    "source up file://$UP main|frobnicate up x|2" \
    "source up file://$UP main|skill up|2" \
    "source up file://$UP main|skill up skills/alpha extra|2" \
    "source up file://$UP main extra|skill up skills/alpha|1" \
    "source up file://$UP main|skill up ../escape|2" \
    "source up file://$UP main|skill up /abs/alpha|2" \
    "source up file://$UP main|skill up skills/../../alpha|2" \
    "source up file://$UP main|source up file://$UP main|2" \
    "source _up file://$UP main|skill _up skills/alpha|1"; do
    local l1="${bad%%|*}" rest="${bad#*|}"
    local l2="${rest%%|*}" n="${rest##*|}"
    conf "$l1" "$l2"
    run "$PLUG" sync
    [ "$status" -eq 1 ] || {
      echo "accepted: $l1 / $l2"
      return 1
    }
    [[ "$output" == *"plugins.conf:$n:"* ]] || {
      echo "wrong line for: $l1 / $l2 -> $output"
      return 1
    }
    [ ! -e "$TK/vendor" ]
    [ ! -e "$TK/plugins.lock" ]
  done
}

@test "plug conf: the same skill line twice is a name collision, refused before fetching" {
  conf "source up file://$UP main" "skill up skills/alpha" "skill up skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"'alpha' claimed twice"* ]] || false
  [ ! -e "$PLUG_CACHE_DIR" ] # refused before any network work
  [ ! -e "$TK/vendor" ]
}

@test "plug conf: a '_'-prefixed or dot-prefixed skill name is refused, never half-vendored" {
  mkdir -p "$UP/skills/_private" "$UP/skills/.dot"
  skill_md _private >"$UP/skills/_private/SKILL.md"
  skill_md dot >"$UP/skills/.dot/SKILL.md"
  git -C "$UP" add -A
  git -C "$UP" commit -q -m underscore
  local p
  for p in skills/_private skills/.dot; do
    conf "source up file://$UP main" "skill up skills/alpha" "skill up $p"
    run "$PLUG" sync
    [ "$status" -eq 1 ]
    [[ "$output" == *"install.sh would skip it"* ]] || false
    [ ! -e "$TK/vendor" ]
    [ ! -e "$TK/plugins.lock" ]
    run "$PLUG" sync --check
    [ "$status" -eq 1 ]
  done
}

@test "plug: sync with no plugins.conf refuses and leaves vendor/ and the lock alone" {
  std_conf
  "$PLUG" sync >/dev/null
  local before
  before="$(snapshot)"
  rm "$TK/plugins.conf"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"no plugins.conf"* ]] || false
  [ "$(snapshot)" = "$before" ]
  # and --check does not call that state clean
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
}

@test "plug: a comments-only conf with nothing vendored syncs, checks and lists cleanly" {
  conf "# nothing yet"
  run_clean "$PLUG" sync
  [ ! -e "$TK/vendor" ]
  [ ! -e "$TK/plugins.lock" ]
  run_clean "$PLUG" sync --check
  run_clean "$PLUG" doctor
  run_clean "$PLUG" list
}

@test "plug: the whole flow runs under /bin/bash 3.2 with set -u and empty arrays" {
  [ -x /bin/bash ] || skip "no /bin/bash"
  /bin/bash -c '((BASH_VERSINFO[0] == 3))' || skip "/bin/bash is not 3.x"
  conf "# empty"
  run_clean /bin/bash "$PLUG" sync
  run_clean /bin/bash "$PLUG" sync --check
  run_clean /bin/bash "$PLUG" doctor
  std_conf
  run_clean /bin/bash "$PLUG" sync
  run_clean /bin/bash "$PLUG" update
  conf "source up file://$UP main" # a source with no skills
  run_clean /bin/bash "$PLUG" sync
  [ ! -e "$TK/vendor/skills/alpha" ]
  run_clean /bin/bash "$PLUG" sync --check
  run_clean /bin/bash "$PLUG" list
}

@test "plug ref: an annotated tag pins the commit it peels to; update follows a moved tag" {
  git -C "$UP" tag -a v1 -m v1
  local v1
  v1="$(git -C "$UP" rev-parse HEAD)"
  conf "source up file://$UP v1" "skill up skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  grep -q "^source up $v1 " "$TK/plugins.lock"
  printf 'v2\n' >>"$UP/skills/alpha/SKILL.md"
  git -C "$UP" commit -q -am v2
  git -C "$UP" tag -f -a v1 -m v1-moved >/dev/null
  run "$PLUG" update
  [ "$status" -eq 0 ]
  grep -q "^source up $(git -C "$UP" rev-parse HEAD) " "$TK/plugins.lock"
  grep -q v2 "$TK/vendor/skills/alpha/SKILL.md"
}

@test "plug ref: a non-main branch ref pins that branch, not the default branch" {
  git -C "$UP" checkout -q -b dev
  printf 'dev\n' >>"$UP/skills/alpha/SKILL.md"
  git -C "$UP" commit -q -am dev
  local dev
  dev="$(git -C "$UP" rev-parse HEAD)"
  git -C "$UP" checkout -q main
  conf "source up file://$UP dev" "skill up skills/alpha"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  grep -q "^source up $dev " "$TK/plugins.lock"
  grep -q dev "$TK/vendor/skills/alpha/SKILL.md"
}

@test "plug upstream: a force-push that drops the locked SHA fails clearly without a cache" {
  std_conf
  "$PLUG" sync >/dev/null
  # rewrite history: the locked commit is no longer reachable from any ref
  git -C "$UP" commit -q --amend -m rewritten
  git -C "$UP" reflog expire --expire=now --all
  git -C "$UP" gc -q --prune=now
  rm -rf "$PLUG_CACHE_DIR" "$TK/vendor/skills/beta" # beta must be re-fetched
  cp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  local before
  before="$(snapshot)"
  run "$PLUG" sync
  [ "$status" -eq 1 ]
  [[ "$output" == *"not found"*"plug update up"* ]] || false
  [ "$(snapshot)" = "$before" ]
  cmp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  [ -z "$(find "$TK" -name '.plug-stage.*')" ]
  # update re-pins onto the rewritten history
  run "$PLUG" update
  [ "$status" -eq 0 ]
  grep -q "^source up $(git -C "$UP" rev-parse HEAD) " "$TK/plugins.lock"
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug atomicity: a failure on the second skill leaves the first skill and the lock untouched" {
  std_conf
  "$PLUG" sync >/dev/null
  cp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  local before
  before="$(snapshot)"
  # upstream: alpha changes cleanly, beta gains an export-ignore extraction cannot honour
  printf 'v2\n' >>"$UP/skills/alpha/SKILL.md"
  printf 'scripts/deep/notes.txt export-ignore\n' >"$UP/skills/beta/.gitattributes"
  git -C "$UP" add -A
  git -C "$UP" commit -q -m v2
  run "$PLUG" update
  [ "$status" -eq 1 ]
  [[ "$output" == *"does not hash"* ]] || false
  [ "$(snapshot)" = "$before" ]
  cmp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  run grep -q v2 "$TK/vendor/skills/alpha/SKILL.md"
  [ "$status" -ne 0 ]
  [ -z "$(find "$TK" -name '.plug-stage.*')" ]
}

@test "plug: a user git config with core.autocrlf=true still syncs byte-exact copies" {
  # BUG (bin/plug:406): git archive applies core.autocrlf/eol conversion, so the
  # extracted copy no longer hashes to the upstream tree and every sync fails.
  printf '[core]\n\tautocrlf = true\n' >"$GIT_CONFIG_GLOBAL"
  std_conf
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  run grep -c $'\r' "$TK/vendor/skills/alpha/SKILL.md"
  [ "$output" = 0 ]
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug: in-tree eol/ident attributes do not alter the vendored bytes" {
  printf '*.md eol=crlf ident\n' >"$UP/skills/alpha/.gitattributes"
  # shellcheck disable=SC2016  # literal keyword for git's ident attribute
  printf '$Id$\n' >>"$UP/skills/alpha/SKILL.md"
  git -C "$UP" add -A
  git -C "$UP" commit -q -m attrs
  std_conf
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  cmp "$TK/vendor/skills/alpha/SKILL.md" <(git -C "$UP" cat-file blob HEAD:skills/alpha/SKILL.md)
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug: a plugins.conf saved with CRLF line endings parses" {
  printf 'source up file://%s main\r\nskill up skills/alpha\r\n' "$UP" >"$TK/plugins.conf"
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ -f "$TK/vendor/skills/alpha/SKILL.md" ]
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug atomicity: a rename failing mid-apply rolls vendor/ back to its previous state" {
  std_conf
  "$PLUG" sync >/dev/null
  cp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  local before stub="$BATS_TEST_TMPDIR/stub"
  before="$(snapshot)"
  printf 'v2\n' >>"$UP/skills/alpha/SKILL.md"
  printf 'v2\n' >>"$UP/skills/beta/SKILL.md"
  git -C "$UP" add -A
  git -C "$UP" commit -q -m v2
  # mv fails once, moving the new beta into vendor/ — after alpha already landed
  mkdir -p "$stub"
  # shellcheck disable=SC2016  # the stub's own $2/$@
  printf '#!/bin/sh\ncase "$2" in */vendor/skills/beta) if [ ! -e "%s/tripped" ]; then : >"%s/tripped"; exit 1; fi ;; esac\nexec /bin/mv "$@"\n' \
    "$stub" "$stub" >"$stub/mv"
  chmod +x "$stub/mv"
  PATH="$stub:$PATH" run "$PLUG" update
  [ "$status" -ne 0 ]
  [ -e "$stub/tripped" ]
  [ "$(snapshot)" = "$before" ]
  cmp "$TK/plugins.lock" "$BATS_TEST_TMPDIR/lock.1"
  [ -z "$(find "$TK" -name '.plug-stage.*')" ]
}

@test "plug: an upstream branch deleted after sync fails update instead of resolving stale" {
  git -C "$UP" branch dev
  conf "source up file://$UP dev" "skill up skills/alpha"
  "$PLUG" sync >/dev/null
  git -C "$UP" branch -D dev >/dev/null
  run "$PLUG" update
  [ "$status" -eq 1 ]
  [[ "$output" == *"ref 'dev' not found"* ]] || false
}

@test "plug: an unbound-variable abort exits non-zero, under bash 3.2 too" {
  mkdir -p "$BATS_TEST_TMPDIR/bin"
  # shellcheck disable=SC2016  # the injected unset expansion
  sed 's/^  list) cmd_list ;;$/  list) echo "$plug_test_unset" ;;/' "$PLUG" >"$BATS_TEST_TMPDIR/bin/plug"
  grep -q plug_test_unset "$BATS_TEST_TMPDIR/bin/plug"
  run bash "$BATS_TEST_TMPDIR/bin/plug" list
  [ "$status" -ne 0 ]
  if [ -x /bin/bash ]; then
    run /bin/bash "$BATS_TEST_TMPDIR/bin/plug" list
    [ "$status" -ne 0 ]
  fi
}

@test "plug: dotfiles, spaced names and odd dot-names are vendored and hashed exactly" {
  printf 'node_modules\n' >"$UP/skills/alpha/.gitignore"
  printf 'odd\n' >"$UP/skills/alpha/..odd"
  printf 'spaced\n' >"$UP/skills/alpha/has space.md"
  mkdir -p "$UP/skills/alpha/.hidden"
  printf 'h\n' >"$UP/skills/alpha/.hidden/x"
  git -C "$UP" add -A
  git -C "$UP" commit -q -m dots
  std_conf
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ -f "$TK/vendor/skills/alpha/.gitignore" ]
  [ -f "$TK/vendor/skills/alpha/..odd" ]
  [ -f "$TK/vendor/skills/alpha/has space.md" ]
  [ -f "$TK/vendor/skills/alpha/.hidden/x" ]
  rm -rf "$PLUG_CACHE_DIR"
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
  # a hand-dropped dotfile is drift too
  printf 'x\n' >"$TK/vendor/skills/alpha/.extra"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
}

@test "plug: a skill bigger than a pipe buffer survives archive|tar under pipefail" {
  head -c 2000000 /dev/zero | tr '\0' 'a' >"$UP/skills/alpha/big.txt"
  local i
  for ((i = 0; i < 300; i++)); do printf '%s\n' "$i" >"$UP/skills/alpha/f$i"; done
  git -C "$UP" add -A
  git -C "$UP" commit -q -m big
  std_conf
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ "$(wc -c <"$TK/vendor/skills/alpha/big.txt" | tr -d ' ')" -eq 2000000 ]
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug: an upstream symlink or submodule is refused, nothing vendored" {
  ln -s /etc/hosts "$UP/skills/beta/abs-link"
  git -C "$UP" add -A
  git -C "$UP" commit -q -m links
  std_conf
  run "$PLUG" sync
  [ "$status" -ne 0 ]
  [[ "$output" == *"symlink or submodule"* ]] || false
  [ ! -e "$TK/vendor" ]
  [ ! -e "$TK/plugins.lock" ]
}

@test "plug: a lock tree edited to match a hand-edited vendor/ is caught by sync (cached) and verify" {
  std_conf
  "$PLUG" sync >/dev/null
  printf 'injected\n' >>"$TK/vendor/skills/alpha/SKILL.md"
  local forged
  git init -q "$BATS_TEST_TMPDIR/h"
  cp -R "$TK/vendor/skills/alpha/." "$BATS_TEST_TMPDIR/h/"
  git -C "$BATS_TEST_TMPDIR/h" add -A
  forged="$(git -C "$BATS_TEST_TMPDIR/h" write-tree)"
  sed -E "s/^(skill up skills\/alpha alpha) [0-9a-f]+$/\1 $forged/" "$TK/plugins.lock" >"$TK/lock.new"
  mv "$TK/lock.new" "$TK/plugins.lock"
  run "$PLUG" sync --check # offline check alone cannot tell
  [ "$status" -eq 0 ]
  run "$PLUG" sync
  [ "$status" -ne 0 ]
  [[ "$output" == *"lock edited by hand"* ]] || false
  rm -rf "$PLUG_CACHE_DIR"
  run "$PLUG" verify
  [ "$status" -ne 0 ]
  [[ "$output" == *"lock edited by hand"* ]] || false
}

@test "plug verify: passes on an honest lock, fetching on a cache miss" {
  std_conf
  "$PLUG" sync >/dev/null
  rm -rf "$PLUG_CACHE_DIR"
  run_clean "$PLUG" verify
  [[ "$output" == *"pinned upstream commits"* ]] || false
}

@test "plug --check: a lock whose sha is a branch name is malformed" {
  std_conf
  "$PLUG" sync >/dev/null
  sed -E 's/^(source up) [0-9a-f]+ /\1 main /' "$TK/plugins.lock" >"$TK/lock.new"
  mv "$TK/lock.new" "$TK/plugins.lock"
  run "$PLUG" sync --check
  [ "$status" -ne 0 ]
  [[ "$output" == *"malformed"* ]] || false
}

@test "plug: sync removes stray files and dot-entries that --check reports" {
  std_conf
  "$PLUG" sync >/dev/null
  touch "$TK/vendor/skills/.DS_Store" "$TK/vendor/skills/notes.txt"
  mkdir "$TK/vendor/skills/..x"
  run "$PLUG" sync --check
  [ "$status" -ne 0 ]
  [[ "$output" == *"..x"* ]] || false
  run_clean "$PLUG" sync
  [ ! -e "$TK/vendor/skills/.DS_Store" ]
  [ ! -e "$TK/vendor/skills/notes.txt" ]
  [ ! -e "$TK/vendor/skills/..x" ]
  run_clean "$PLUG" sync --check
}

@test "plug: the repo .gitignore never drops a vendored upstream file" {
  local f
  for f in vendor/skills/x/.env.example vendor/skills/x/aws-credentials.md vendor/skills/x/k.pem vendor/skills/x/.vscode/a; do
    run git -C "$REPO_ROOT" check-ignore -q --no-index "$f"
    [ "$status" -eq 1 ]
  done
}

@test "plug --check: a lock skill the conf no longer names is drift" {
  std_conf
  "$PLUG" sync >/dev/null
  conf "source up file://$UP main" "skill up skills/alpha" # hand-edited, not synced
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"plugins.lock lists beta, which plugins.conf no longer names"* ]] || false
}

@test "plug --check: a lock source the conf no longer names is drift" {
  std_conf
  "$PLUG" sync >/dev/null
  printf 'source ghost %s 2000-01-01\n' "$(git -C "$UP" rev-parse HEAD)" >>"$TK/plugins.lock"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"pins source ghost"* ]] || false
}

@test "plug --check: a stray file or dot-dir in vendor/skills is drift" {
  std_conf
  "$PLUG" sync >/dev/null
  mkdir -p "$TK/vendor/skills/.cache"
  printf 'x\n' >"$TK/vendor/skills/.cache/f"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"vendor/skills/.cache is not in plugins.conf"* ]] || false
  rm -rf "$TK/vendor/skills/.cache"
  printf 'x\n' >"$TK/vendor/skills/notes.txt"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"vendor/skills/notes.txt is not in plugins.conf"* ]] || false
}

@test "plug --check: a vendored skill replaced by a symlink is drift, and sync restores a real dir" {
  std_conf
  "$PLUG" sync >/dev/null
  mv "$TK/vendor/skills/alpha" "$BATS_TEST_TMPDIR/alpha-real"
  ln -s "$BATS_TEST_TMPDIR/alpha-real" "$TK/vendor/skills/alpha"
  run "$PLUG" sync --check
  [ "$status" -eq 1 ]
  run "$PLUG" sync
  [ "$status" -eq 0 ]
  [ -d "$TK/vendor/skills/alpha" ]
  [ ! -L "$TK/vendor/skills/alpha" ]
  [ -f "$BATS_TEST_TMPDIR/alpha-real/SKILL.md" ] # the link target was not touched
  run "$PLUG" sync --check
  [ "$status" -eq 0 ]
}

@test "plug --check: a malformed lock is a failure, not a pass" {
  std_conf
  "$PLUG" sync >/dev/null
  printf 'garbage line here\n' >>"$TK/plugins.lock"
  run "$PLUG" sync --check
  [ "$status" -ne 0 ]
  [[ "$output" == *"plugins.lock:"*"malformed"* ]] || false
}
